[workspace.package]
edition = "2021"

[workspace]
resolver = "2"
members = [
    "nest-client",
    "nest-server"
]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
log = "0.4.20"