[package]
name = "nest-server"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
ngrok = { version="0.13", features=["axum"] }
tokio = { version = "1.26", features = ["full"] }
axum = "0.6"
anyhow = "1.0"